name: Build Dataverse Package

on:
  release:
    types: [published]
# on:
#   push:
#     tags:
#       - 'v*.*.*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-file: './build/dataverse_solution_managed.zip'
          solution-folder: './package'
          solution-type: 'Managed'

      - name: Upload built solution to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/dataverse_solution_managed.zip
          asset_name: dataverse_solution_managed.zip
          asset_content_type: application/zip
