name: Build Dataverse Package

on:
  release:
    types: [published]
env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}
  #version
  majorVersion: 1
  minorVersion: 0
  buildVersion: ${{ github.run_number }}
  buildType: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Get Solution Unique Name
        id: solution-unique-name
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: package/Other/Solution.xml
          xpath: "//ImportExportXml/SolutionManifest/UniqueName"

      - name: Update Solution Version
        run: |
          $version = "${{env.majorVersion}}.${{env.minorVersion}}.${{ env.buildVersion }}"
          $xml = [xml](Get-Content package/other/Solution.xml)
          $xml.Solution.Version = $version
          $xml.Save("package/other/Solution.xml")
        shell: pwsh

      - name: Get Solution Version
        id: solution-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: package/Other/Solution.xml
          xpath: "//ImportExportXml/SolutionManifest/Version"

      - name: Pack Solution
        uses: microsoft/powerplatform-actions/pack-solution@v1
        with:
          solution-file: "./build/${{ steps.solution-unique-name.outputs.info }}_${{ steps.solution-version.outputs.info }}_managed.zip"
          solution-folder: "./package"
          solution-type: "Managed"

      - name: Upload built solution to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/${{ steps.solution-unique-name.outputs.info }}_${{ steps.solution-version.outputs.info }}_managed.zip
          asset_name: ${{ steps.solution-unique-name.outputs.info }}_${{ steps.solution-version.outputs.info }}_managed.zip
          asset_content_type: application/zip
